#Acceptance Criteria:
	# # Verify that 'Create' button is visible on the 'Requests for Quotation' page
	# # Verify that when 'Create' button is pressed, system takes the user to new request creation page
	# # Verify that the system presents the following for order creation:
	# ## Vendor (dropdown box, produces pre-determined list of vendors)
	# ## Vendor Reference (optional, text box for vendor related information)
	# ## Order Date (dropdown calendar, format displayed is MM/DD/YYYY 24:59:59
	# ## Table for Products selection (visible by default, see 'Products Table' UAC)
	# ## Deliveries & Invoices (selectible, see 'Deliveries & Invoices' UAC)
	# ## Text box for notes (displays text 'Define your terms and conditions ...')
	# ## Untaxed Amount (automated calculator displaying total amount before taxes)
	# ## Taxes (automated calculator displaying total amount of taxes)
	# ## Total (automated calculator displaying grand total amount, with taxes)"
	# # Verify that 'Vendor' dropdown box contains vendor information previously created
	# # Verify that 'Order Date' dropdown displays the date and time the order creation is initiated per format
	# # Verify that 'Order Date' dropdown displays calendar upon being clicked and allows selection of a different date
	# # Verify that 'Vendor Reference' text input is available and accepts user input
	# # Verify that 'Products' section is visible by default and the following columns are displayed:
	# ## Product
	# ## Description
	# ## Scheduled Date
	# ## Quantity
	# ## Unit Price
	# ## Taxes
	# ## Subtotal
	# # Verify that 'Products' section has 'Add an item' clickable text that produces the following upon click:
	# ## Drag&Drop sign (allows the order of products changed if there is more than 1 product within the table)
	# ## Product dropdown box (contains product names per database)
	# ## Description text box (allows user to input information)
	# ## Scheduled Date dropdown box (generates calendar for day selection)
	# ## Quantity text input box ('0.00' displayed by default, allows user to input quantity with a floating number)
	# ## Unit Price text input box ('0.00' displayed by default, allows user to input price with a floating number)
	# ## Taxes dropdown box (generates applicable tax rates defined by law)
	# ## Subtotal (automated calculator displaying the total for the single item)
	# # Verify that 'Deliveries & Invoices' section has the following upon click:
	# ## Scheduled Date dropdown box (produces selectible calendar upon click)
	# ## Incoterm dropdown box (produces selectible options upon click)
	# ## Billing Status text (autogenerated text area stating the billing status)
	# ## Payment Terms dropdown box (generates the following options to choose from:
	# ### Immediate Payment
	# ### 15 Days
	# ### 30 Net Days
	# ### End of Following Month
	# ### 30% Advance End of Following Month)
	# ## Fiscal Position dropdown box (generates options pre-determined within the database)
	# # Verify that 'Terms and conditions' text input box is displayed and has the following text by default:
	#Define your terms and conditions ...
	# # Verify that 'Untaxed Amount' is displayed and it automatically generates the total amount before taxes
	# # Verify that 'Taxes' is displayed and it automatically generates the total taxes calculated per the tax ratio determined for each added item
	# # Verify that 'Total' is displayed and it automatically generates the total with taxes

@BRIT-3992 @McLean @Purchases @regression
Feature: As a POS Manager, I should be able to 'Create' new 'Request for Quotation'

  Background: go to 'Requests for Quotation' page
    Given the "user" is logged in
    When the user clicks on Purchases
    Then the user should be on the Purchases page
    And the 'Requests for Quotation' should be displayed on the main panel

  Scenario: Verify that 'Create' button is visible on the 'Requests for Quotation' page
    Then the system should display Create button

  Scenario: Verify that when 'Create' button is pressed, the system takes the user to new request creation page
    When the user clicks Create button
    Then the page title is New - Odoo

  Scenario: Verify that the system displays Vendor dropdown box
    When the user clicks Create button
    Then the system should display Vendor dropdown box

  Scenario: Verify that 'Vendor' dropdown box contains vendor information previously created
    Given the user clicks Create button
    And the system should display Vendor dropdown box
    And the Vendor dropdown box is blank by default
    When the user clicks on Vendor dropdown box
    Then the Vendor dropdown box displays list of Vendors

  Scenario: Verify that 'Vendor Reference' text input is available and it accepts user input
    When the user clicks Create button
    Then the system should display Vendor Reference text input
    And the Vendor Reference text input is blank
    And the Vendor Reference text input accepts user input
    And the Vendor Reference text input stores user input

  Scenario: Verify that 'Products' section is visible by default and the given list of column headers are displayed
    When the user clicks Create button
    Then the system should display Products section
    And the Products sections should have the given "<headers>"
      | <headers>      |
      | Product        |
      | Description    |
      | Scheduled Date |
      | Quantity       |
      | Unit Price     |
      | Taxes          |
      | Subtotal       |